apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-app-configmap
data:
  application.yml: |- 
    spring:
      data:
        mongodb:
          host: mongodb-service.default.svc.cluster.local
          port: 27017
          database: test_db
          # uri: mongodb://mongodb-service.default.svc.cluster.local:27017/test_db
          authentication-database: admin
          username: '${SECRET_MONGODB_USERNAME}'
          password: '${SECRET_MONGODB_PASSWORD}'